# 本地运行的配置文件
[Server]
AppMode = "debug"   # debug 开发环境, release 生产环境
BackPort = ":8765"  # 后台服务端口
FrontPort = ":5678" # 前台服务端口

[JWT]
Secret = "abc123321"
Expire = 24             # 过期时间 (小时)
Issuer = "gin-vue-blog"

[Mysql]
Host = "127.0.0.1"
Port = "3306"
Config = ""         # 其他配置, 例如时区
Dbname = "gvb"      # 数据库名称
Username = "root"
Password = "root" # 数据库密码
# 日志级别 silent, error, warn, info, 默认 info
LogMode = "error" # silent 相当于关闭日志

[Redis]
DB = 7
Addr = '127.0.0.1:6379'
Password = ''

[Session]
Name = "mysession"
Salt = "salt"
MaxAge = 600       # 秒

# 配置发送验证码账号信息
[Email]
Host = "smtp.163.com"       # 服务器地址, 例如 smtp.qq.com 前往要发邮件的邮箱查看其 smtp 协议
Port = 465                  # 前往要发邮件的邮箱查看其 smtp 协议端口, 大多为 465
From = ""     # 发件人 (邮箱)
IsSSL = true                # 是否开启 SSL
Secret = "" # 密钥, 不是邮箱登录密码, 是开启 smtp 服务后获取的一串验证码
Nickname = ""           # 发件人昵称, 通常为自己的邮箱名

[Captcha]
SendEmail = true # 通过邮箱发送验证码
ExpireTime = 15  # 过期时间 (分钟)

[Zap]
Level = "error"            # 日志级别: debug, info, warn, error, dpanic, panic, fatal, 默认 info
Format = "console"         # 输出格式: console, json
Prefix = "[GIN-VUE-BLOG] " # 日志前缀
Directory = "log"          # 存放日志的文件夹
ShowLine = true            # 是否显示哪行调用
LogInConsole = true        # 是否输出到控制台

[Upload]
OssType = "local"             # 控制存储: local、qiniu
Path = "public/uploaded"      # 本地文件访问路径 (OssType="local" 才生效)
StorePath = "public/uploaded" # 本地文件上传路径 (OssType="local" 才生效)
# Markdown 目前只支持本地上传 (目前使用前端导出, 该配置无效)
MdPath = "public/markdown/"      # Markdown 访问路径
MdStorePath = "public/markdown/" # Markdown 上传路径

[Qiniu]
ImgPath = ""          # 外链
Zone = ""
Bucket = ""
AccessKey = ""
SecretKey = ""
UseHttps = false      # 是否使用 https 加速
UseCdnDomains = false # 上传是否使用 CDN 上传加速
